// ignore_for_file: non_constant_identifier_names
// ignore_for_file: camel_case_types
// ignore_for_file: prefer_single_quotes

// This file is automatically generated. DO NOT EDIT, all your changes would be lost.
import 'package:flutter/material.dart' show debugPrint;
import 'package:rxnet_example/bean/normal_water_info_entity.dart';
import 'package:rxnet_example/bean/water_info_entity.dart';

JsonConvert jsonConvert = JsonConvert();
typedef JsonConvertFunction<T> = T Function(Map<String, dynamic> json);

class JsonConvert {
	static final Map<String, JsonConvertFunction> _convertFuncMap = {
		(WaterInfoEntity).toString(): WaterInfoEntity.fromJson,
		(WaterInfoForecast).toString(): WaterInfoForecast.fromJson,
		(WaterInfoYesterday).toString(): WaterInfoYesterday.fromJson,
    (NormalWaterInfoEntity).toString(): NormalWaterInfoEntity.fromJson,
    (NormalWaterInfoCityInfo).toString(): NormalWaterInfoCityInfo.fromJson,
    (NormalWaterInfoData).toString(): NormalWaterInfoData.fromJson,
    (NormalWaterInfoDataForecast).toString(): NormalWaterInfoDataForecast.fromJson,
    (NormalWaterInfoDataYesterday).toString(): NormalWaterInfoDataYesterday.fromJson,
	};

  T? convert<T>(dynamic value) {
    if (value == null) {
      return null;
    }
    return asT<T>(value);
  }

  List<T?>? convertList<T>(List<dynamic>? value) {
    if (value == null) {
      return null;
    }
    try {
      return value.map((dynamic e) => asT<T>(e)).toList();
    } catch (e, stackTrace) {
      debugPrint('asT<$T> $e $stackTrace');
      return <T>[];
    }
  }

  List<T>? convertListNotNull<T>(dynamic value) {
    if (value == null) {
      return null;
    }
    try {
      return (value as List<dynamic>).map((dynamic e) => asT<T>(e)!).toList();
    } catch (e, stackTrace) {
      debugPrint('asT<$T> $e $stackTrace');
      return <T>[];
    }
  }

  T? asT<T extends Object?>(dynamic value) {
    if (value is T) {
      return value;
    }
    final String type = T.toString();
    try {
      final String valueS = value.toString();
      if (type == "String") {
        return valueS as T;
      } else if (type == "int") {
        final int? intValue = int.tryParse(valueS);
        if (intValue == null) {
          return double.tryParse(valueS)?.toInt() as T?;
        } else {
          return intValue as T;
        }
      } else if (type == "double") {
        return double.parse(valueS) as T;
      } else if (type == "DateTime") {
        return DateTime.parse(valueS) as T;
      } else if (type == "bool") {
        if (valueS == '0' || valueS == '1') {
          return (valueS == '1') as T;
        }
        return (valueS == 'true') as T;
      } else if (type == "Map" || type.startsWith("Map<")) {
        return value as T;
      } else {
        if (_convertFuncMap.containsKey(type)) {
          return _convertFuncMap[type]!(value) as T;
        } else {
          throw UnimplementedError('$type unimplemented');
        }
      }
    } catch (e, stackTrace) {
      debugPrint('asT<$T> $e $stackTrace');
      return null;
    }
  }

	//list is returned by type
	static M? _getListChildType<M>(List<Map<String, dynamic>> data) {
		if(<WaterInfoEntity>[] is M){
			return data.map<WaterInfoEntity>((Map<String, dynamic> e) => WaterInfoEntity.fromJson(e)).toList() as M;
		}
		if(<WaterInfoForecast>[] is M){
			return data.map<WaterInfoForecast>((Map<String, dynamic> e) => WaterInfoForecast.fromJson(e)).toList() as M;
		}
		if(<WaterInfoYesterday>[] is M){
			return data.map<WaterInfoYesterday>((Map<String, dynamic> e) => WaterInfoYesterday.fromJson(e)).toList() as M;
		}

    if(<NormalWaterInfoEntity>[] is M){
      return data.map<NormalWaterInfoEntity>((Map<String, dynamic> e) => NormalWaterInfoEntity.fromJson(e)).toList() as M;
    }
    if(<NormalWaterInfoCityInfo>[] is M){
      return data.map<NormalWaterInfoCityInfo>((Map<String, dynamic> e) => NormalWaterInfoCityInfo.fromJson(e)).toList() as M;
    }
    if(<NormalWaterInfoData>[] is M){
      return data.map<NormalWaterInfoData>((Map<String, dynamic> e) => NormalWaterInfoData.fromJson(e)).toList() as M;
    }
    if(<NormalWaterInfoDataForecast>[] is M){
      return data.map<NormalWaterInfoDataForecast>((Map<String, dynamic> e) => NormalWaterInfoDataForecast.fromJson(e)).toList() as M;
    }
    if(<NormalWaterInfoDataYesterday>[] is M){
      return data.map<NormalWaterInfoDataYesterday>((Map<String, dynamic> e) => NormalWaterInfoDataYesterday.fromJson(e)).toList() as M;
    }


    debugPrint("${M.toString()} not found");
	
		return null;
}

	static M? fromJsonAsT<M>(dynamic json) {
		if (json is List) {
			return _getListChildType<M>(json.map((e) => e as Map<String, dynamic>).toList());
		} else {
			return jsonConvert.asT<M>(json);
		}
	}
}